### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by webscrooge** [KriskotooBG/antiToolbox#1]
> ParseError: "syntax error, unexpected '"kriskotooBG\AntiToolbox"' (T_CONSTANT_ENCAPSED_STRING), expecting '{'" (EXCEPTION) in "plugins/antiToolbox-master (3).phar/src/kriskotooBG/AntiToolbox/Main" at line 2

**Comment by KriskotooBG** [comment]
yeah, small mistake... It's fixed now :)
